language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0.0'; fi
  - pip install coveralls pytest pytest-cov
# command to install dependencies
install: "python setup.py install"

script: py.test --cov=PyBeacon tests/