dist: trusty
sudo: false

language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - pip install coveralls pytest pytest-cov
# command to install dependencies
install: "python setup.py install"

script: py.test